name: Nginx Triple Sequential Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: First Build
      run: |
        echo "Starting build 1"
        docker build -t my-nginx-image:${{ github.sha }}-1 .
        docker run --rm my-nginx-image:${{ github.sha }}-1 nginx -t
        docker rmi my-nginx-image:${{ github.sha }}-1
        echo "Finished build 1"

  build2:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: First Build
      run: |
        echo "Starting build 1"
        docker build -t my-nginx-image:${{ github.sha }}-1 .
        docker run --rm my-nginx-image:${{ github.sha }}-1 nginx -t
        docker rmi my-nginx-image:${{ github.sha }}-1
        echo "Finished build 1"         
  build7:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: First Build
      run: |
        echo "Starting build 1"
        docker build -t my-nginx-image:${{ github.sha }}-1 .
        docker run --rm my-nginx-image:${{ github.sha }}-1 nginx -t
        docker rmi my-nginx-image:${{ github.sha }}-1
        echo "Finished build 1"      
        
  build3:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v2
  
      - name: First Build
        run: |
          echo "Starting build 1"
          docker build -t my-nginx-image:${{ github.sha }}-1 .
          docker run --rm my-nginx-image:${{ github.sha }}-1 nginx -t
          docker rmi my-nginx-image:${{ github.sha }}-1
          echo "Finished build 1"
  build36:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: First Build
      run: |
        echo "Starting build 1"
        docker build -t my-nginx-image:${{ github.sha }}-1 .
        docker run --rm my-nginx-image:${{ github.sha }}-1 nginx -t
        docker rmi my-nginx-image:${{ github.sha }}-1
        echo "Finished build 1"

  build22:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: First Build
      run: |
        echo "Starting build 1"
        docker build -t my-nginx-image:${{ github.sha }}-1 .
        docker run --rm my-nginx-image:${{ github.sha }}-1 nginx -t
        docker rmi my-nginx-image:${{ github.sha }}-1
        echo "Finished build 1"         
  build27:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: First Build
      run: |
        echo "Starting build 1"
        docker build -t my-nginx-image:${{ github.sha }}-1 .
        docker run --rm my-nginx-image:${{ github.sha }}-1 nginx -t
        docker rmi my-nginx-image:${{ github.sha }}-1
        echo "Finished build 1"      
        
  build13:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v2
  
      - name: First Build
        run: |
          echo "Starting build 1"
          docker build -t my-nginx-image:${{ github.sha }}-1 .
          docker run --rm my-nginx-image:${{ github.sha }}-1 nginx -t
          docker rmi my-nginx-image:${{ github.sha }}-1
          echo "Finished build 1"         
