name: Nginx Triple Sequential Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: First Build
      run: |
        echo "Starting build 1"
        docker build -t my-nginx-image:${{ github.sha }}-1 .
        docker run --rm my-nginx-image:${{ github.sha }}-1 nginx -t
        docker rmi my-nginx-image:${{ github.sha }}-1
        echo "Finished build 1"

    - name: Second Build
      run: |
        echo "Starting build 2"
        docker build -t my-nginx-image:${{ github.sha }}-2 .
        docker run --rm my-nginx-image:${{ github.sha }}-2 nginx -t
        docker rmi my-nginx-image:${{ github.sha }}-2
        echo "Finished build 2"

    - name: Third Build
      run: |
        echo "Starting build 3"
        docker build -t my-nginx-image:${{ github.sha }}-3 .
        docker run --rm my-nginx-image:${{ github.sha }}-3 nginx -t
        docker rmi my-nginx-image:${{ github.sha }}-3
        echo "Finished build 3"
  build2:
    runs-on: self-hosted
    strategy:
      matrix:
        build-number: [1, 2, 3, 4, 5, 6]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        echo "Building docker for build number: ${{ matrix.build-number }}"
        docker build -t test-${{ matrix.build-number }} .        
